### ISSUE TITLE
Unable to compile Script

### ISSUE THREAD

**Issue by waseeld** [GiacomoLaw/Keylogger#136] opened 2023-08-15 15:18 UTC
```
PS C:\Users\PC\Desktop\Keylogger-master\windows> mingw32-gcc.exe .\klog_main.cpp
.\klog_main.cpp: In function 'int Save(int)':
.\klog_main.cpp:132:57: error: 'strcpy_s' was not declared in this scope
    strcpy_s(lastwindow, sizeof(lastwindow), window_title);
                                                         ^
.\klog_main.cpp:137:23: error: 'localtime_s' was not declared in this scope
    localtime_s(&tm, &t);
```
                       ^
i saw https://github.com/GiacomoLaw/Keylogger/issues/99 but it dosent help me lol

**Comment by GiacomoLaw** [comment] 2023-10-04 07:56
Using MinGW? Localtime_s doesn't work on stuff outside Windows compilers.

Try adding this:

`define localtime_r(T,Tm) (localtime_s(Tm,T) ? NULL : Tm)`

Does this help?

**Comment by GiacomoLaw** [comment] 2023-10-04 07:58
Duplicate of #133

**Closed by GiacomoLaw** 2023-10-04 07:58 UTC
Labels: bug, windows
